git:
  depth: 3
env:
  global:
  - secure: "mD3RBWzc5aThrUKa60flWefcyZf2RWqtz15x7/keuIuVZVLs6pxxJr2W5jAY945iJRxSpvkiWYaa4ADjcNUitJ2xSaF9K9onn83QD7i03+4fyptqa7ZU3CJx+J+BmiKQT4vbFhzMEjxwHWQsQ5ufXeEW+O1irJl/IEUUpJPsn7eaiwR6Ke5HfhCQ13M/efHceewKfvUMcMPkL3xPAyzgor5QEns7UNUdSGUPplrNGYOoy8p1F6WSwhF1c0OymhN7RMGRvG2krgOeyFaw7lQeIjJZoU1xRb0GSydAF/EiL18bCSyxOfQtVHoPVurQ6OZYamV6qP7SbdIJyFewvcp2wUH7h8DgGbie2/fOw2CpjhSJqyqWWHZdvZJt0gM4MA/CtdDre5M6SUIq0FrNC+qIF6ROfcwvlUpcOfV78bo4UWo6aBV0CvJ5KmZl6fCiAUhjuOMVCnx6SHrrjiyD1YPa7pDLRenHM66rrttgI+39WvuF1cInCD/XOinNy7gbxE+gA2OtVhKQCixaTFchLPuG8lrLTIhyteHk+D/FaP0TeF2sTJ4coze1M1XuXCyDlHEc+lgMsR0zNNtgAQeQANVeKh9ITkJWfxELLv7S/W9axySWseWxC0S4Y2PN0JALcAZjNwq73uLWCgiOPHIs+ygVlYEUHyTOPDHHcR6LEOeMBpo="
  - secure: "grDEa1Q6hFWa72y9Ljh4oxzGECH3ELCByPpljWPdvesbNWQy2vZ1rMV0ri/LlLG10wNnofG78558TwSZTJ088gqdeUZn/a9A2QPsIFijXR6Tsr4oT6bXbbjxyp/akLOSDUcQnAAlUZBDn8DkKkgrCda7sDlOBj3/RWYHcXy7O2Fn0h3IZ8TAKEH4ImLBFIaXEnGJghGHKKtuLVUj234rZv1oXRzpQnE+rMOBUF+hhjoTymc6wurI3vs9rIGfOwLXXrJ45LQFN69b4iIm0+nuwISUsOJ3+bZL0QlZRpW4lwSKq2TXJWFdGYd5flwF9D+ZQ6Bz02q8pZsKNCcJBzBoJS4JslQiGRNhj7SQZd/6e9SiDzOupFFjTLgLLpXubXqw4AHPYJ+hJiasbYOV9XBI8rPT8NKY7w/zRbKExNW2LymckEj5v8BSGPaNMeTJ/ly7txX3qrra5ogmvY82kXJjo9w4YJ9bCj8ZONegAhN7b5BxSubbt9bCjKdvSEZKKmsEBKF/bCY9KgLoRDzJ4WYTNHQtnZNpbL4D6xmiytkmNQCgSMZxt6C8tWq5hjmk9v65M7v+7GdfXvC6c1rzH/raYmF6R7RrH82R1CMMKiLBHFGAYtE/OXbsYOHr0ROefGvmE8igzwafhDe4sIJbs/4ZO2KpbmsSaeV0RfDVefobipM="

language: objective-c
osx_image: xcode9.2
compiler: clang

before_install:
- brew update

install:
- brew install awscli

script:
- mkdir build
- cd build
- cmake -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 ..
- cmake --build .
- strip -u -r code/libassimp.dylib
- "aws s3 cp code/libassimp.dylib s3://build.lwjgl.org/nightly/macosx/x64/ --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
- "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git"
- "aws s3 cp revision.git s3://build.lwjgl.org/nightly/macosx/x64/libassimp.dylib.git --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""